/* Local design fixture. No calls to the running Jelly API or user filesystem. */
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const species=['jellyfish','octopus','whale','sea-turtle','crab','pufferfish','seahorse','manta-ray','starfish','seal','clownfish','nudibranch'];
const avatar=(i,cls='')=>`<img class="avatar ${cls}" src="../brand/avatars/${String(i+1).padStart(2,'0')}-${species[i]}.png" alt="">`;
const mark='<img src="../brand/logo/jelly-mark.png" alt="">';
let projects=[{id:'website',name:'Website',cwd:'/home/alex/work/website'},{id:'personal',name:'Personal',cwd:'/home/alex/personal'},{id:'research',name:'Research',cwd:'/home/alex/research'}];
let agents=[{id:'milo',name:'Milo',role:'Build something lovely',avatar:1,project:'website',cwd:'/home/alex/work/website'},{id:'pearl',name:'Pearl',role:'A fresh pair of eyes',avatar:3,project:'website',cwd:'/home/alex/work/website'},{id:'fin',name:'Fin',role:'Make sense of the details',avatar:2,project:'research',cwd:'/home/alex/research'},{id:'pip',name:'Pip',role:'Your everyday helper',avatar:4,project:null,cwd:'/home/alex/.jelly/workspaces/pip'}];
let scope='website',selected='milo',drafts={},memory={},dialog=null,state='ready',showList=false,chosenAvatar=1,folder='/home/alex/work',projectDraft={name:'',cwd:''},agentDraft={name:'',role:''},folderReturn='create-project',returnFocus=null,timers=[],newMessage='',search='';
const app=$('#app'), live=$('#announcement');
const agent=()=>agents.find(a=>a.id===selected)||agents[0];
const project=()=>projects.find(p=>p.id===scope);
const scopeName=()=>scope==='all'?'All agents':scope==='ungrouped'?'Ungrouped':project()?.name||'Website';
const btn=(text,action,style='')=>`<button class="btn ${style}" data-action="${action}">${text}</button>`;
const ib=(name,label,action)=>`<button class="icon-btn" aria-label="${label}" data-action="${action}">${icon(name)}</button>`;
const busy=()=>['working','streaming','cancelling'].includes(state);
function announce(s){live.textContent=s;}
function scopeAgents(){return agents.filter(a=>(scope==='all'||(scope==='ungrouped'?!a.project:a.project===scope))&&a.name.toLowerCase().includes(search.toLowerCase()));}
function projectButton(cls=''){return `<button class="project-trigger ${cls}" data-action="switcher" aria-haspopup="dialog" aria-expanded="${dialog==='switcher'}">${icon('folder')}<span class="scope-name">${esc(scopeName())}</span>${icon('chevron-down')}</button>`;}
function render(){
 const a=agent();app.classList.toggle('show-list',showList);app.innerHTML=`<aside class="side" aria-label="Agents"><div class="side-brand"><button class="brand" style="border:0;background:none" data-action="easter" aria-label="Jelly">${mark}jelly</button>${ib('plus','New agent','create-agent')}</div>${projectButton()}<h1 class="mobile-list-title">Your agents</h1><div class="agent-search">${icon('search')}<input class="search" aria-label="Search agents" placeholder="Find an agent" value="${esc(search)}"></div><nav class="agent-list" aria-label="Agent conversations">${state==='project-empty'?'<div class="empty-list">No agents in this project yet.</div>':scopeAgents().map(x=>`<button class="agent-row ${x.id===selected?'selected':''}" data-agent="${x.id}" aria-current="${x.id===selected?'true':'false'}">${avatar(x.avatar)}<span class="grow"><strong>${esc(x.name)}</strong><small>${x.id===selected&&busy()?'Working…':esc(x.role)}</small></span><span class="activity">${x.id==='milo'?'now':x.id==='pearl'?'12m':''}</span></button>`).join('')||'<div class="empty-list">No matching agents.</div>'}</nav><button class="archive-button" data-action="archived">${icon('archive')}Archived agents</button><div class="sidebar-footer wave"><div class="row"><span class="badge ${state==='offline'?'warning':'good'}"><i class="dot"></i>${state==='offline'?'Offline':'Connected'}</span><span class="grow"></span>${ib('settings','Settings','settings')}</div><div class="connection-text muted">Your workspace, a little brighter.</div></div></aside><section class="conversation-shell" aria-label="Conversation"><header class="chat-header"><button class="icon-btn mobile-back" data-action="inbox">${icon('chevron-left')}Agents</button>${projectButton('small-project')}${avatar(a.avatar)}<div class="header-identity"><strong>${esc(a.name)}</strong><div class="subline">${busy()?'Working':state==='sudo'||state==='handoff'?'Needs you':'Ready'}<span>·</span>${esc(scopeName())}</div></div><div class="right-actions"><button class="btn quiet" data-action="computer">${icon('monitor')}<span class="computer-label">Computer</span></button>${ib('ellipsis','Agent options','edit-agent')}</div></header>${['offline','reconnecting'].includes(state)?`<div class="banner" role="status">${icon('wifi-off')}<span class="grow">${state==='offline'?'You’re offline. Your draft is safe.':'Reconnecting… Your conversation will catch up.'}</span>${btn('Retry','reconnect')}</div>`:''}<div class="chat-scroll"><div class="reading">${conversation()}</div></div>${composer()}</section>`;
 if(dialog)renderDialog();
 $('#app .search')?.addEventListener('input',e=>{const pos=e.target.selectionStart;search=e.target.value;render();const input=$('#app .search');input.focus();input.setSelectionRange(pos,pos);});
 $('#message')?.addEventListener('input',e=>{drafts[selected]=e.target.value;const send=$('[data-action=send]');if(send)send.disabled=!e.target.value.trim()||state==='offline';});
 $('#message')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&app.dataset.device!=='mobile'){e.preventDefault();send();}});
}
function composer(){return `<div class="composer-area"><div class="composer">${ib('plus','Conversation tools','tools')}<textarea id="message" aria-label="Message ${esc(agent().name)}" placeholder="Message ${esc(agent().name)}…" rows="1" ${state==='connection'?'disabled':''}>${esc(drafts[selected]||'')}</textarea>${busy()?`<button class="icon-btn send" data-action="stop" aria-label="Stop working" ${state==='cancelling'?'disabled':''}>${icon('square')}</button>`:`<button class="icon-btn send" data-action="send" aria-label="Send message" ${!drafts[selected]?.trim()||state==='offline'?'disabled':''}>${icon('arrow-up')}</button>`}</div><div class="composer-foot"><button data-action="model">GPT-5.4 ${icon('chevron-down')}</button><span class="desktop-hint">Enter to send · Shift + Enter for a new line</span></div></div>`;}
function working(label='Milo is working',detail='Making room for the good stuff.'){return `<div class="working-row" role="status"><span class="jelly-working" data-state="${busy()?'working':'idle'}">${mark}</span><div><strong>${label}</strong><small>${detail}</small></div></div>`;}
function conversation(){
 if(state==='connection')return `<div class="empty">${mark}<h2>A little help, connected.</h2><p>Connect an account to start a conversation with your agents.</p>${btn('Connect account','login','primary')}</div>`;
 if(state==='agent-empty'||state==='project-empty')return `<div class="empty">${state==='agent-empty'?avatar(agent().avatar,'large'):mark}<h2>${state==='agent-empty'?`Hello, I’m ${esc(agent().name)}.`:'A fresh space for your ideas.'}</h2><p>${state==='agent-empty'?'Tell me what you’re working on. We can take it from there.':'Add your first agent to '+esc(scopeName())+'. New agents will start in this project’s folder.'}</p>${state==='project-empty'?`<div class="path">${esc(project()?.cwd||'/home/alex/work/website')}</div><br>${btn('Create agent','create-agent','primary')}`:btn('Help me get started','suggestion')}</div>`;
 if(state==='loading')return `<div role="status" aria-label="Loading conversation"><div class="skeleton" style="height:64px;width:68%;margin:20px 0 40px auto"></div>${[95,80,90,55].map(w=>`<div class="skeleton" style="height:16px;width:${w}%;margin:18px 0"></div>`).join('')}<p class="small muted">Loading your conversation…</p></div>`;
 let html=state==='history'?`<p class="muted small" role="status">Loading earlier messages…</p>`:`<div class="day">Today</div>`;
 html+=`<div class="user-message">${esc(newMessage||'Let’s give the homepage a little more personality. Something warm, clear, and unmistakably us.')}</div><div class="message-meta">You · 10:42</div>`;
 if(state==='working'||state==='cancelling')return html+working(state==='cancelling'?'Stopping…':esc(agent().name)+' is working',state==='cancelling'?'Finishing the current step safely.':'Reviewing the homepage and sketching a few ideas.');
 if(['sudo','handoff','error','interrupted','cancelled'].includes(state)){
 const info={sudo:['Permission needed','Milo needs permission to install a dependency. Review the exact command before continuing.','Approve once','approve'],handoff:['Your turn in the browser','Complete the sign-in in Computer. Your agent will wait until you’re ready.','Open Computer','computer-human'],error:['That step didn’t finish','The service returned an error. Your conversation and files are still here.','Try again','retry'],interrupted:['Work was interrupted','The server restarted before this run finished. Review the last step, then resume when you’re ready.','Resume','retry'],cancelled:['Stopped by you','Completed steps are saved. Send a message whenever you’re ready.','Continue','retry']}[state];
 return html+`<div class="notice ${state==='error'?'error':state==='sudo'?'warning':''}"><h3>${info[0]}</h3><p>${info[1]}</p>${state==='sudo'?'<pre>sudo apt-get install imagemagick</pre><p class="caption">Requested by Milo · Website</p>':''}<div class="row wrap">${btn(info[2],info[3],'primary')}${state==='sudo'?btn('Deny','deny'):''}</div></div>`;
 }
 html+=`<div class="assistant-message">${avatar(agent().avatar)}<div class="answer">${state==='streaming'?'<p>I’m bringing a little more warmth into the homepage, starting with a simpler introduction and a softer blue palette.</p><span class="typing-dot" aria-label="Writing"></span>':`<div class="activity-row">${icon('check')}Reviewed 3 files · Updated the homepage</div><h2>A warmer welcome.</h2><p>I gave the homepage a softer palette and a little more breathing room. The important things still come first.</p><ul><li>A clearer introduction, with one easy next step.</li><li>Friendly details that feel at home with your brand.</li><li>A layout that works just as well on a small screen.</li></ul>${state==='long'?'<h3>A few implementation notes</h3><pre class="long-code">export const theme = {\n  accent: "#0964DA",\n  readingWidth: 720,\n  respectReducedMotion: true\n};</pre><p>Long paths wrap without pushing the conversation wider: <code>/home/alex/work/website/components/homepage/WelcomePanel.tsx</code></p>':''}${state==='tool'?'<details open><summary>Updated homepage.tsx · 3 files</summary><pre>✓ Checked the existing layout\n✓ Updated spacing and colours\n✓ Previewed at 390 and 1440 pixels</pre></details><br>':''}<button class="artifact-card" data-action="preview">${icon('file-text')}<span class="grow" style="text-align:left"><strong>Homepage refresh</strong><small>Preview · 3 files updated</small></span>${icon('chevron-right')}</button><div class="message-actions">${ib('copy','Copy response','copy')}${ib('refresh-cw','Try another response','retry')}</div>`}</div></div>`;
 return html;
}
function field(label,id,value='',hint='',type='text'){return `<label class="field">${label}<input id="${id}" type="${type}" value="${esc(value)}">${hint?`<span class="hint">${hint}</span>`:''}</label>`;}
function renderDialog(){
 const title={switcher:'Switch project','create-project':'New project','folder-browser':'Choose a folder','folder-error':'Folder unavailable','project-settings':'Project settings','delete-project':'Delete project?','move-agent':'Move agent','create-agent':'New agent','avatar-picker':'Choose an avatar','edit-agent':'Agent profile',archived:'Archived agents','archive-empty':'Archived agents',settings:'Settings',login:'Connect your account','api-error':'Couldn’t connect',computer:'Computer','computer-human':'Your turn','computer-error':'Computer unavailable',model:'Choose a model',tools:'Conversation tools',preview:'Homepage refresh'}[dialog]||'Jelly';
 let body='';
 if(dialog==='switcher')body=`<input class="search" id="project-search" aria-label="Find a project" placeholder="Find a project…"><div class="project-options">${['all','ungrouped',...projects.map(p=>p.id)].map(id=>`<button class="project-option ${scope===id?'selected':''}" data-scope="${id}">${icon('folder')}<span>${esc(id==='all'?'All agents':id==='ungrouped'?'Ungrouped':projects.find(p=>p.id===id).name)}</span><span class="count">${agents.filter(a=>id==='all'||(id==='ungrouped'?!a.project:a.project===id)).length}</span>${scope===id?icon('check'):''}</button>`).join('')}</div><hr class="rule">${btn(icon('plus')+'New project','create-project','quiet')}${project()?btn('Project settings','project-settings','quiet'):''}`;
 if(dialog==='create-project'||dialog==='project-settings'){const editing=dialog==='project-settings';const p=editing?project()||projects[0]:projectDraft;body=`<p>Keep related agents together. Projects are optional.</p>${field('Project name','project-name',p.name)}<label class="field">Default working directory<span class="path">${esc(p.cwd||'No folder selected')}</span><span class="hint">Choose a folder on the connected Jelly server. New agents will start here.</span></label>${btn(icon('folder')+'Browse folders','browse')} ${editing?'<p class="small" style="margin-top:16px">Changing this folder only affects future agents. Existing agents keep their current directory.</p>':''}<p class="form-error" role="alert"></p><div class="dialog-actions">${editing?btn('Delete project','delete-project','quiet'):btn('Cancel','close')}${btn(editing?'Save changes':'Create project',editing?'save-project':'save-new-project','primary')}</div>`;}
 if(dialog==='folder-browser'||dialog==='folder-error')body=`<p>Folders on <strong>Jelly server</strong></p><div class="path">${esc(folder)}</div><div class="breadcrumbs">${btn(icon('arrow-left')+'Parent folder','folder-up','quiet')}</div>${dialog==='folder-error'?`<div class="notice error">This folder can’t be opened. You may not have permission to access it.</div><br>${btn('Try again','folder-retry')}`:`<div class="folder-list">${(folder==='/home/alex/work'?['website','notes','shared']:folder==='/home/alex'?['work','personal','research']:folder==='/'?['home']:folder==='/home'?['alex']:[]).map(n=>`<button class="folder-row" data-folder="${n}">${icon('folder')}<span class="grow">${n}</span>${icon('chevron-right')}</button>`).join('')||'<p class="muted small">No subfolders. You can use this folder.</p>'}</div>`}<div class="dialog-actions">${btn('Cancel','folder-cancel')}${btn('Use this folder','folder-select','primary')}</div>`;
 if(dialog==='delete-project')body=`<p>Delete <strong>${esc(scopeName())}</strong>? Its agents will move to Ungrouped. Their conversations, files, and working directories will stay exactly where they are.</p><div class="dialog-actions">${btn('Keep project','close')}${btn('Delete project','confirm-delete','danger')}</div>`;
 if(dialog==='move-agent')body=`<p>Choose a group for ${esc(agent().name)}. Moving an agent won’t change its working directory.</p><div class="path">${esc(agent().cwd)}</div><br>${[{id:'ungrouped',name:'Ungrouped'},...projects].map(p=>`<button class="project-option" data-move="${p.id}">${icon('folder')}${esc(p.name)}${agent().project===p.id?icon('check'):''}</button>`).join('')}`;
 if(dialog==='create-agent'||dialog==='edit-agent'){const editing=dialog==='edit-agent';const a=editing?agent():agentDraft;body=`<div class="form-avatar">${avatar(editing?agent().avatar:chosenAvatar,'large')}${btn('Choose avatar','avatar-picker')}</div>${field('Name','agent-name',a.name)}${field('What should this agent help with?','agent-role',a.role)}<label class="field">Project<span class="path">${editing?esc(projects.find(p=>p.id===agent().project)?.name||'Ungrouped'):esc(scope==='all'?'Ungrouped':scopeName())}</span></label><label class="field">Working directory<span class="path">${esc(editing?agent().cwd:project()?.cwd||'A private workspace will be created')}</span><span class="hint">${editing?'This belongs to the agent and stays the same when moving projects.':project()?'Inherited from '+esc(scopeName())+'.':'No project is required.'}</span></label><p class="form-error" role="alert"></p><div class="dialog-actions">${editing?btn('Move','move-agent'):btn('Cancel','close')}${btn(editing?'Save changes':'Create agent',editing?'save-agent':'save-new-agent','primary')}</div>${editing?`<hr class="rule">${btn('Archive agent','archive','quiet')}`:''}`;}
 if(dialog==='avatar-picker')body=`<p>A small companion for every kind of work.</p><div class="avatar-grid">${species.map((n,i)=>`<button class="avatar-choice ${i===chosenAvatar?'selected':''}" data-avatar="${i}" aria-pressed="${i===chosenAvatar}">${avatar(i)}${n.replaceAll('-',' ')}</button>`).join('')}</div><div class="dialog-actions">${btn('Done','avatar-done','primary')}</div>`;
 if(dialog==='archived'||dialog==='archive-empty')body=dialog==='archive-empty'?'<div class="empty"><h3>Nothing archived.</h3><p>Agents you archive will appear here.</p></div>':`<p>Archived agents keep their conversations and working directories.</p><div class="row">${avatar(9)}<div class="grow"><strong>Scout</strong><br><small class="muted">Archived yesterday · Personal</small></div>${btn('Restore','restore')}</div>`;
 if(dialog==='settings')body=`<div class="mode-row"><div class="grow"><strong>Account</strong><p>Connected · alex@example.com</p></div>${btn('Manage','login')}</div><div class="mode-row"><div class="grow"><strong>Appearance</strong><p>Light, dark, or your device setting</p></div><select id="appearance" aria-label="Appearance"><option>Light</option><option>Dark</option><option>System</option></select></div><div class="mode-row"><div class="grow"><strong>Reduced motion</strong><p>Also follows your device’s preference</p></div><input id="reduce-setting" aria-label="Reduce motion" type="checkbox" ${app.dataset.reduced==='true'?'checked':''}></div><div class="mode-row"><div class="grow"><strong>Server</strong><p>Jelly server · connected</p></div><span class="badge good">Ready</span></div>`;
 if(dialog==='login')body=`<p>Continue in your browser to connect your account. This design demo does not open an authentication service.</p><div class="notice" role="status">Waiting for sign-in…</div><div class="dialog-actions">${btn('Cancel','close')}${btn('Simulate connected','connected','primary')}</div>`;
 if(dialog==='api-error')body=`<div class="notice error">We couldn’t connect to your account. Check the connection and try again.</div><div class="dialog-actions">${btn('Cancel','close')}${btn('Try again','login','primary')}</div>`;
 if(dialog.startsWith('computer'))body=`<div class="computer-preview">${icon('monitor')}<strong>${dialog==='computer-error'?'Preview unavailable':dialog==='computer-human'?'You have control':'Computer is ready'}</strong><span class="small">${dialog==='computer-error'?'The connection was interrupted.':'Browser preview · design fixture'}</span></div><p>${dialog==='computer-human'?'Complete the sign-in, then hand control back to your agent.':'Your agent’s browser appears here when it needs one.'}</p><div class="dialog-actions">${btn('Close','close')}${btn(dialog==='computer-error'?'Reconnect':dialog==='computer-human'?'Done, continue':'Take control',dialog==='computer-error'?'computer':dialog==='computer-human'?'approve':'computer-human','primary')}</div>`;
 if(dialog==='model')body=`<p>Model selection is a fixture in this reference.</p>${btn('GPT-5.4 · selected','close','primary')}`;
 if(dialog==='tools')body=`<p>Open the agent’s computer or inspect its profile.</p><div class="row">${btn('Computer','computer')}${btn('Agent profile','edit-agent')}</div>`;
 if(dialog==='preview')body='<div class="notice"><h3>A little more room for ideas.</h3><p>A fixture preview of the refreshed homepage.</p></div><p style="margin-top:16px">In the application, this card opens the generated artifact.</p>';
 app.insertAdjacentHTML('beforeend',`<div class="overlay ${dialog==='switcher'?'switcher':''}"><section class="dialog sheet-enter" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div class="sheet-grab"></div><div class="dialog-head"><h2 id="dialog-title">${title}</h2>${ib('x','Close dialog','close')}</div>${body}</section></div>`);
 for(const el of app.children)if(!el.classList.contains('overlay'))el.inert=true;
 $('#project-search')?.addEventListener('input',e=>{document.querySelectorAll('[data-scope]').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(e.target.value.toLowerCase()));});
 $('#appearance')?.addEventListener('change',e=>setTheme(e.target.value==='System'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):e.target.value.toLowerCase()));
 $('#reduce-setting')?.addEventListener('change',e=>{app.dataset.reduced=e.target.checked;$('#motion-toggle').checked=e.target.checked;});
 setTimeout(()=>$('.dialog input:not([type=checkbox]), .dialog button')?.focus(),0);
}
let avatarReturn='create-agent';
function openDialog(d){if(!dialog)returnFocus=document.activeElement?.getAttribute('data-action');dialog=d;render();}
function closeDialog(){dialog=null;render();const target=returnFocus&&app.querySelector(`[data-action="${returnFocus}"]`);target?.focus();}
function preserveForms(){if($('#project-name'))projectDraft={name:$('#project-name').value,cwd:projectDraft.cwd};if($('#agent-name'))agentDraft={name:$('#agent-name').value,role:$('#agent-role').value};}
function send(){if(!drafts[selected]?.trim()||busy()||state==='offline')return;newMessage=drafts[selected];drafts[selected]='';state='working';render();announce('Message sent. '+agent().name+' is working.');timers.push(setTimeout(()=>{state='streaming';render();},1800),setTimeout(()=>{state='ready';render();announce('Response ready.');},4000));}
function clearTimers(){timers.forEach(clearTimeout);timers=[];}
function toast(s){announce(s);const el=document.createElement('div');el.className='toast';el.textContent=s;app.appendChild(el);setTimeout(()=>el.remove(),3000);}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.agent){memory[scope]=b.dataset.agent;selected=b.dataset.agent;showList=false;state='ready';render();return;}
 if(b.dataset.scope){memory[scope]=selected;scope=b.dataset.scope;search='';selected=memory[scope]||scopeAgents()[0]?.id||selected;state=scopeAgents().length?'ready':'project-empty';dialog=null;render();announce(scopeName()+' selected');return;}
 if(b.dataset.folder){folder=(folder==='/'?'':folder)+'/'+b.dataset.folder;openDialog('folder-browser');return;}
 if(b.dataset.avatar){chosenAvatar=+b.dataset.avatar;render();return;}
 if(b.dataset.move){agent().project=b.dataset.move==='ungrouped'?null:b.dataset.move;scope=b.dataset.move;closeDialog();toast('Agent moved. Working directory unchanged.');return;}
 const action=b.dataset.action;
 if(action==='close'){closeDialog();return;}
 if(action==='inbox'){showList=true;render();return;}
 if(action==='send'){send();return;}
 if(action==='stop'){clearTimers();state='cancelling';render();timers.push(setTimeout(()=>{state='cancelled';render();announce('Work stopped.');},650));return;}
 if(['retry','approve'].includes(action)){dialog=null;state='working';render();timers.push(setTimeout(()=>{state='ready';render();announce('Response ready.');},2000));return;}
 if(action==='deny'){state='cancelled';render();announce('Permission denied.');return;}
 if(action==='suggestion'){drafts[selected]='Help me plan the first step.';render();$('#message').focus();return;}
 if(action==='reconnect'){state='reconnecting';render();timers.push(setTimeout(()=>{state='ready';render();announce('Connected. Draft restored.');},1400));return;}
 if(action==='browse'){preserveForms();folderReturn=dialog;folder=projectDraft.cwd||project()?.cwd||'/home/alex/work';openDialog('folder-browser');return;}
 if(action==='folder-up'){folder=folder.slice(0,folder.lastIndexOf('/'))||'/';openDialog('folder-browser');return;}
 if(action==='folder-retry'){openDialog('folder-browser');return;}
 if(action==='folder-cancel'){openDialog(folderReturn);return;}
 if(action==='folder-select'){projectDraft.cwd=folder;if(folderReturn==='project-settings')pendingCwd=folder;openDialog(folderReturn);if(folderReturn==='project-settings'){document.querySelector('.dialog .path').textContent=folder;$('#project-name').value=projectDraft.name||project()?.name;}return;}
 if(action==='save-new-project'||action==='save-project'){const name=$('#project-name').value.trim();const cwd=action==='save-project'?(pendingCwd||project()?.cwd):projectDraft.cwd;if(!name||!cwd){$('.form-error').textContent=!name?'Give your project a name.':'Choose a working directory to continue.';$('#project-name').setAttribute('aria-invalid',!name);return;}if(action==='save-project'){project().name=name;project().cwd=cwd;}else{const p={id:'project-'+Date.now(),name,cwd};projects.push(p);scope=p.id;state='project-empty';}projectDraft={name:'',cwd:''};pendingCwd=null;closeDialog();toast(action==='save-project'?'Project updated. Existing agents keep their directories.':'Project created.');return;}
 if(action==='confirm-delete'){const id=scope;agents.forEach(a=>{if(a.project===id)a.project=null;});projects=projects.filter(p=>p.id!==id);scope='ungrouped';closeDialog();toast('Project deleted. Agents moved to Ungrouped.');return;}
 if(action==='avatar-picker'){preserveForms();avatarReturn=dialog==='edit-agent'?'edit-agent':'create-agent';chosenAvatar=avatarReturn==='edit-agent'?agent().avatar:chosenAvatar;openDialog(action);return;}
 if(action==='avatar-done'){openDialog(avatarReturn);if(avatarReturn==='edit-agent'){document.querySelector('.form-avatar img').src=`../brand/avatars/${String(chosenAvatar+1).padStart(2,'0')}-${species[chosenAvatar]}.png`;$('#agent-name').value=agentDraft.name;$('#agent-role').value=agentDraft.role;}return;}
 if(action==='save-new-agent'||action==='save-agent'){const name=$('#agent-name').value.trim(),role=$('#agent-role').value.trim();if(!name){$('.form-error').textContent='Give your agent a name.';$('#agent-name').setAttribute('aria-invalid','true');return;}if(action==='save-agent'){Object.assign(agent(),{name,role,avatar:chosenAvatar});}else{const id='agent-'+Date.now();agents.push({id,name,role:role||'Ready to help',avatar:chosenAvatar,project:project()?.id||null,cwd:project()?.cwd||'/home/alex/.jelly/workspaces/'+id});selected=id;state='agent-empty';}agentDraft={name:'',role:''};showList=false;closeDialog();toast(action==='save-agent'?'Profile updated.':'Agent created in '+agent().cwd);return;}
 if(action==='archive'){closeDialog();toast('Archive action previewed. Use the Archived agents screen for restore.');return;}
 if(action==='restore'){closeDialog();toast('Scout restored.');return;}
 if(action==='connected'){state='agent-empty';closeDialog();toast('Account connected.');return;}
 if(action==='copy'){navigator.clipboard?.writeText('A warmer welcome. I gave the homepage a softer palette and a little more breathing room.').then(()=>toast('Response copied.'),()=>toast('Copy is unavailable in this browser.'));return;}
 if(action==='easter'){b.classList.remove('avatar-bob');void b.offsetWidth;b.classList.add('avatar-bob');toast('A tiny hello from the sea.');return;}
 if(action==='create-project')projectDraft={name:'',cwd:''};
 if(action==='create-agent'){agentDraft={name:'',role:''};chosenAvatar=1;}
 if(action==='edit-agent')chosenAvatar=agent().avatar;
 openDialog(action);
});
let pendingCwd=null;
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openDialog('switcher');}if(e.key==='Escape'&&dialog){e.preventDefault();closeDialog();}if(e.key==='Tab'&&dialog){const f=[...document.querySelectorAll('.dialog button:not(:disabled),.dialog input,.dialog select,.dialog textarea')].filter(x=>!x.hidden&&x.getClientRects().length);if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0]?.focus();}}});
function setTheme(t){document.documentElement.dataset.theme=t;$('#theme-select').value=t;}
function selectScreen(id){clearTimers();const s=SCREENS.find(s=>s.id===id)||SCREENS[0];state=s.state;dialog=s.dialog;showList=state==='inbox';scope='website';selected='milo';search='';newMessage='';app.dataset.device=s.device;$('#device-select').value=s.device;setTheme(s.theme);if(state==='offline')drafts[selected]='Can you check the mobile layout too?';if(s.id==='project-settings')pendingCwd=null;if(s.id==='folder-browser')folder='/home/alex/work';render();$('#screen-select').value=s.id;history.replaceState(null,'',`?screen=${s.id}&device=${app.dataset.device}&theme=${s.theme}`);}
$('#screen-select').innerHTML=SCREENS.map(s=>`<option value="${s.id}">${s.title}</option>`).join('');$('#screen-select').addEventListener('change',e=>selectScreen(e.target.value));$('#device-select').addEventListener('change',e=>{app.dataset.device=e.target.value;render();});$('#theme-select').addEventListener('change',e=>setTheme(e.target.value));$('#motion-toggle').addEventListener('change',e=>app.dataset.reduced=e.target.checked);
const params=new URLSearchParams(location.search);selectScreen(params.get('screen'));if(params.has('device')){app.dataset.device=params.get('device');$('#device-select').value=params.get('device');}if(params.has('theme'))setTheme(params.get('theme'));
